name: 'get-pr-info'
description: 'A GitHub Action that get last commit, body and author in current pull-request'
inputs:
  token:
    description: 'A token with access to your repository scoped in as a secret'
    required: true
outputs:
  body:
    description: 'body in pr'
  title:
    description: 'title of pr'
  commits:
    description: 'commits in pr'
runs:
  using: 'node12'
  main: 'index.js'
